### PR TITLE
Fix home layout (issue #9).

### PR DESCRIPTION
**Pull request by feitosa-daniel**
The home page was missing a couple of lines (#9).

### CODE REVIEW

**Review by mauricioaniche — COMMENTED** [review]
I can't remember why I put two in first place. I think there was a minor issue, but I suppose you tested it, and everything looks good, right?

**Comment by feitosa-daniel** [comment]
I checked if there was anything misplaced between to previous and new versions and all seemed good.

But I also found that I missed a closing div when I created the quotes some time ago (:sweat_smile:).

**Comment by mauricioaniche** [comment]
So this means I can merge this one?

**Comment by feitosa-daniel** [comment]
Yeap. :)

**Pull request merged**
